config/routes.rb
Rails.application.routes.draw do
  resources :reservation_details
  devise_for :users
  get 'pages/index'

  get 'pages/calendar'

  get 'pages/reservation'

  root to: 'pages#calendar'

  get '/redirect', to: 'google#redirect', as: 'redirect'
  get '/callback', to: 'google#callback', as: 'callback'
  get '/calendars', to: 'google#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'google#events', as: 'events', calendar_id: /[^\/]+/
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation_detail.rb
class ReservationDetail < ApplicationRecord
    belongs_to :user
    validates_presence_of :title, :body
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :ta], multiple: false)                                      ##
  ############################################################################################ 
  has_many :reservation_details

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/google_controller.rb
class GoogleController < ApplicationController
    def redirect
      client = Signet::OAuth2::Client.new({
        client_id: ENV.fetch("GOOGLE_CLIENT_ID"),
        client_secret: ENV.fetch("GOOGLE_CLIENT_SECRET"),
        authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
        scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
        redirect_uri: callback_url
      })
  
      redirect_to client.authorization_uri.to_s
    end
  
    def callback
        client = Signet::OAuth2::Client.new({
          client_id: ENV.fetch("GOOGLE_CLIENT_ID"),
          client_secret: ENV.fetch("GOOGLE_CLIENT_SECRET"),
          token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
          redirect_uri: callback_url,
          code: params[:code]
        })
    
        response = client.fetch_access_token!
    
        session[:authorization] = response
    
        redirect_to calendars_url
      end

      def calendars
        client = Signet::OAuth2::Client.new({
          client_id: ENV.fetch("GOOGLE_CLIENT_ID"),
          client_secret: ENV.fetch("GOOGLE_CLIENT_SECRET"),
          token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
        })
    
        client.update!(session[:authorization])
    
        service = Google::Apis::CalendarV3::CalendarService.new
        service.authorization = client
    
        @calendar_list = service.list_calendar_lists
      end

      def events
        client = Signet::OAuth2::Client.new({
          client_id: ENV.fetch("GOOGLE_CLIENT_ID"),
          client_secret: ENV.fetch("GOOGLE_CLIENT_SECRET"),
          token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
        })
    
        client.update!(session[:authorization])
    
        service = Google::Apis::CalendarV3::CalendarService.new
        service.authorization = client
    
        @event_list = service.list_events(params[:calendar_id])
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  access user: :all, admin: :all, ta: :all
  def index
    @reservation_details = ReservationDetail.all
  end

  def calendar
  end

  def reservation
    @reservation_detail = ReservationDetail.new
  end
end

app/controllers/reservation_details_controller.rb
class ReservationDetailsController < ApplicationController
    before_action :find_reservation_detail, only: [:destroy]

    def create
        @reservation_detail = ReservationDetail.new(reservation_params)
        @reservation_detail.user_id = current_user.id

        respond_to do |format|
            if @reservation_detail.save
                format.html {redirect_to pages_index_path, notice: "Reserveration confirmed."}
            else
                format.html {redirect_to pages_reservation_path}
            end
        end
    end

    def destroy
        @reservation_detail.destroy
    end



    private

    def reservation_params
        params.require(:reservation_detail).permit(:title, :body)
    end

    def find_reservation_detail
        @reservation_detail = ReservationDetail.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/google_calendar_helper.rb
require 'googleauth'
require 'google/apis/calendar_v3'

module GoogleCalendarHelper
	
  attr_reader :calendar
  SCOPE = ["https://www.googleapis.com/auth/calendar"]
  CALENDAR_ID = '3qonl2mhums56pqd588s3mqjv4@group.calendar.google.com'
	
  def initializea
	@calendar = Google::Apis::CalendarV3::CalendarService.new
	# get_application_default forces the use of this environment variable.
	# Set it to the location of your JSON credentials.
	ENV["GOOGLE_APPLICATION_CREDENTIALS"] = "./DevcampTAScheduler-f1b651e8766a.json"
	@calendar.authorization = Google::Auth.get_application_default(SCOPE)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservation_details_helper.rb
module ReservationDetailsHelper
end

app/views/google/calendars.html.erb
<ul>
  <% @calendar_list.items.each do |calendar| %>
    <li><%= calendar.summary %> (<%= calendar.id %>)</li>
    <li><%= link_to 'Events', events_path(calendar.id) %> </li>
  <% end %>
</ul>

app/views/google/events.html.erb
<% @event_list.items.each do |event| %>
<br>
***************
<br>
    <% details = JSON.parse(event.to_json) %>
        <% details.each do |attendee| %>
            <% attendee.each do |email, status| %>
                <%= "#{email} #{status}" %>
                
            <% end %>
            <br>
        <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <title>TeamOneApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>    

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
  <footer>
    <div class="container-fluid footer-bottega">
      <p>A PROUD PRODUCT OF BOTTEGA</p>
    </div> 
  </footer>
</html>

app/views/pages/calendar.html.erb
<div class="container title-heading">
  <p>TUTOR SCHEDULING</p>
  <p class="subheading">Select a TA to see their available times</p>
</div>

<div class="container ta-row">
  <div class="row">
		<main class="col-md-12" role="main">
			<section class="row text-center placeholders">

			  <div class="col-6 col-sm-2 placeholder">

			  <%= image_tag 'becky.jpeg', width: "100", height: "100", class: "ta-images" %>
			    <h4>Label</h4>
			    <span="text-muted">Something else</span>
			  </div>

			  <div class="col-6 col-sm-2 placeholder">
			      <%= image_tag 'chillpill.png', width: "100", height: "100", class: "ta-images" %>
			    <h4>Label</h4>
			    <span class="text-muted">Something else</span>
			  </div>

			  <div class="col-6 col-sm-2 placeholder">
			    <%= image_tag 'sneezy.png', width: "100", height: "100", class: "ta-images" %>
			    <h4>Label</h4>
			    <span class="text-muted">Something else</span>
			  </div>

			  <div class="col-6 col-sm-2 placeholder">
			      <%= image_tag 'thetaste.png', width: "100", height: "100", class: "ta-images" %>
			    <h4>Label</h4>
			    <span class="text-muted">Something else</span>
			  </div>

			  <div class="col-6 col-sm-2 placeholder">
			     <%= image_tag 'becky.jpeg', width: "100", height: "100", class: "ta-images" %>
			    <h4>Label</h4>
			    <span class="text-muted">Something else</span>
			  </div>

			  <div class="col-6 col-sm-2 placeholder">
			     <%= image_tag 'thetaste.png', width: "100", height: "100", class: "ta-images" %>
			    <h4>Label</h4>
			    <span class="text-muted">Something else</span>

			  </div>
			</section>
		</main>
	</div>
</div>

<div class="container ta-calendar">
	<div id="myCarousel" class="carousel slide">
	  <!-- Carousel items -->
		<div class="carousel-inner row">
			<div class="item"><p class="carousel-dates">Sunday</p></div>
			<div class="item"><p class="carousel-dates">Monday</p></div>
			<div class="item"><p class="carousel-dates">Tuesday</p></div>
			<div class="item"><p class="carousel-dates">Wednesday</p></div>
			<div class="item"><p class="carousel-dates">Thursday</p></div>
			<div class="item"><p class="carousel-dates">Friday</p></div>
			<div class="item"><p class="carousel-dates">Saturday</p></div>
		</div>
	  <!-- Carousel nav -->
	  <a class="carousel-control left" data-slide="prev">&lsaquo;</a>
	  <a class="carousel-control right" data-slide="next">&rsaquo;</a>
	</div>
	<p class="calendar-title">Select the time you would like to meet</p>
	<div class="col-md-2 buttons">
		<button type="button" class="btn btn-outline-success btn-block time-buttons">9:00 am</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">10:00 am</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">11:00 am</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">12:00 pm</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">1:00 pm</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">2:00 pm</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">3:00 pm</button>
		<button type="button" class="btn btn-outline-success btn-block time-buttons">4:00 pm</button>
	</div>
</div>

app/views/pages/index.html.erb

<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= @reservation_details.inspect %>


app/views/pages/reservation.html.erb
<%= link_to '< back', pages_calendar_path, class: "back-button" %>
<div class="container">
    
  <p class="confirm-heading confirm-title">CONFIRM APPOINTMENT</p>
  <p class="subheading confirm-heading">Selected TA: person</p>
  <p class="subheading confirm-heading">Meeting date: Today</p>
  <p class="subheading confirm-heading">Meeting time: RIGHT NOW</p>
  <%= form_for(@reservation_detail) do |f| %>
    <div class="form-group">
      <p>Subject</p>
      <%= f.text_field :title, class: 'form-control', placeholder: "i.e. Need help setting up database" %>
    </div>

    <div class="form-group">
      <p>Notes</p>
      <%= f.text_area :body, class: 'form-control note-text-box', rows: 20, placeholder: "Add any additional information..." %>
    </div>

    <div class="form-group button-confirm">
      <%= f.submit "Reserve", class: 'btn btn-success btn-block' %>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
 <head>
    

    <title>Navbar Template for Bootstrap</title>

  </head>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Devcamp</a>
      <a href="#">home</a>
      <a href="#">Library</a>
      <a href="#">instructor</a>
      <%= link_to "calender", pages_calendar_path %>
    </div>
    <div class="navbar-right">
      <%= link_to "logout", destroy_user_session_path %> 
    </div>
  </div>
</nav>